[project]
name = "choco-pi"
version = "0.1.0"
description = "Raspberry Pi based smart speaker"
authors = [
    {name = "Max Lee", email = "2389838+codesmax@users.noreply.github.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
